services:
  - type: web
    name: pangaprint
    runtime: python3
    buildCommand: pip install -r requirements-server.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn pangaprint.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        fromService:
          type: web
          name: pangaprint
          property: host