services:
  - type: web
    name: printfix
    runtime: python3
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate && gunicorn printfix.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        fromService:
          type: web
          name: printfix
          property: host
      - key: DATABASE_URL
        fromDatabase:
          name: printfix-db
          property: connectionString

  - type: pserv
    name: printfix-db
    runtime: postgresql
    envVarGroups:
      - key: DATABASE_URL
        fromDatabase:
          name: printfix-db
          property: connectionString