# Generated by Django 6.0.5 on 2026-05-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printerprofile',
            name='duplex_mode',
        ),
    ]
