# Generated by Django 6.0.5 on 2026-05-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_printerprofile_duplex_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='category',
            field=models.CharField(choices=[('file_handling', 'File Handling'), ('processing', 'PDF Processing'), ('output', 'Output & Printing'), ('monitoring', 'Monitoring & Logging'), ('performance', 'Performance'), ('advanced', 'Advanced')], default='advanced', max_length=50),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='choices_json',
            field=models.TextField(blank=True, help_text='JSON array of choice options for choice type'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_value',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='help_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System settings cannot be deleted via UI'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='setting_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('choice', 'Choice'), ('list', 'List')], default='text', max_length=20),
        ),
    ]
