# Generated by Django 6.0.5 on 2026-05-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_systemsettings_category_systemsettings_choices_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printerprofile',
            name='auto_print',
        ),
        migrations.RemoveField(
            model_name='printerprofile',
            name='reverse_pages',
        ),
        migrations.AddField(
            model_name='printerprofile',
            name='processing_mode',
            field=models.CharField(choices=[('normal', 'Normal Order'), ('reverse', 'Reverse Pages')], default='normal', help_text='How to process the PDF pages', max_length=20),
        ),
    ]
